<?php

/**
 * BaseMGGalleryPhoto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $gallery_id
 * @property integer $photo_id
 * @property MGGallery $MGGallery
 * @property MGPhoto $MGPhoto
 * 
 * @method integer        getGalleryId()  Returns the current record's "gallery_id" value
 * @method integer        getPhotoId()    Returns the current record's "photo_id" value
 * @method MGGallery      getMGGallery()  Returns the current record's "MGGallery" value
 * @method MGPhoto        getMGPhoto()    Returns the current record's "MGPhoto" value
 * @method MGGalleryPhoto setGalleryId()  Sets the current record's "gallery_id" value
 * @method MGGalleryPhoto setPhotoId()    Sets the current record's "photo_id" value
 * @method MGGalleryPhoto setMGGallery()  Sets the current record's "MGGallery" value
 * @method MGGalleryPhoto setMGPhoto()    Sets the current record's "MGPhoto" value
 * 
 * @package    magic
 * @subpackage model
 * @author     Damian Suarez
 * @version    SVN: $Id: Builder.php 7380 2010-03-15 21:07:50Z jwage $
 */
abstract class BaseMGGalleryPhoto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mdgalledy_gallery_photo');
        $this->hasColumn('gallery_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('photo_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('MGGallery', array(
             'local' => 'gallery_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('MGPhoto', array(
             'local' => 'photo_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}