<?php

/**
 * BaseMGGallery
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $author_id
 * @property string $title
 * @property clob $description
 * @property Doctrine_Collection $Albums
 * @property Doctrine_Collection $Photos
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method integer             getAuthorId()    Returns the current record's "author_id" value
 * @method string              getTitle()       Returns the current record's "title" value
 * @method clob                getDescription() Returns the current record's "description" value
 * @method Doctrine_Collection getAlbums()      Returns the current record's "Albums" collection
 * @method Doctrine_Collection getPhotos()      Returns the current record's "Photos" collection
 * @method MGGallery           setId()          Sets the current record's "id" value
 * @method MGGallery           setAuthorId()    Sets the current record's "author_id" value
 * @method MGGallery           setTitle()       Sets the current record's "title" value
 * @method MGGallery           setDescription() Sets the current record's "description" value
 * @method MGGallery           setAlbums()      Sets the current record's "Albums" collection
 * @method MGGallery           setPhotos()      Sets the current record's "Photos" collection
 * 
 * @package    magic
 * @subpackage model
 * @author     Damian Suarez
 * @version    SVN: $Id: Builder.php 7380 2010-03-15 21:07:50Z jwage $
 */
abstract class BaseMGGallery extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mdgalledy_gallery');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('author_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('title', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '100',
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('MGAlbum as Albums', array(
             'refClass' => 'MGAlbumGallery',
             'local' => 'gallery_id',
             'foreign' => 'album_id'));

        $this->hasMany('MGPhoto as Photos', array(
             'refClass' => 'MGGalleryPhoto',
             'local' => 'gallery_id',
             'foreign' => 'photo_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}