<?php

/**
 * BaseMGGalleryPhoto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $gallery_id
 * @property integer $photo_id
 * 
 * @method integer        getGalleryId()  Returns the current record's "gallery_id" value
 * @method integer        getPhotoId()    Returns the current record's "photo_id" value
 * @method MGGalleryPhoto setGalleryId()  Sets the current record's "gallery_id" value
 * @method MGGalleryPhoto setPhotoId()    Sets the current record's "photo_id" value
 * 
 * @package    magic
 * @subpackage model
 * @author     Damian Suarez
 * @version    SVN: $Id: Builder.php 7380 2010-03-15 21:07:50Z jwage $
 */
abstract class BaseMGGalleryPhoto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mdgalledy_gallery_photo');
        $this->hasColumn('gallery_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('photo_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}