mg_category:
  class: sfDoctrineRouteCollection
  options:
    model:                MGCategory
    module:               mg_category
    prefix_path:          /mg_category
    column:               id
    with_wildcard_routes: true

mg_gallery:
  class: sfDoctrineRouteCollection
  options:
    model:                MGGallery
    module:               mg_gallery
    prefix_path:          /mg_gallery
    column:               id
    with_wildcard_routes: true

mg_album:
  class: sfDoctrineRouteCollection
  options:
    model:                MGAlbum
    module:               mg_album
    prefix_path:          /mg_album
    column:               id
    with_wildcard_routes: true

mg_photo:
  class: sfDoctrineRouteCollection
  options:
    model:                MGPhoto
    module:               mg_photo
    prefix_path:          /mg_photo
    column:               id
    with_wildcard_routes: true

category:
  class: sfDoctrineRouteCollection
  options:
    model:                Category
    module:               categories
    prefix_path:          /categories
    column:               id
    with_wildcard_routes: true

sf_guard_user:
  class: sfDoctrineRouteCollection
  options:
    model:                sfMooDooUser
    module:               users
    prefix_path:          /users
    column:               id
    with_wildcard_routes: true

page:
  class: sfDoctrineRouteCollection
  options:
    model:                Page
    module:               pages
    prefix_path:          /pages
    column:               id
    with_wildcard_routes: true

event:
  class: sfDoctrineRouteCollection
  options:
    model:                Event
    module:               events
    prefix_path:          /events
    column:               id
    with_wildcard_routes: true

sf_guard_signin:
  url:   /login
  param: { module: sfMooDooAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfMooDooAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfMooDooAuth, action: password }

# default rules
homepage:
  url:   /
  param: { module: pages, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
