generator:
  class: sfDoctrineGenerator
  param:
    model_class:           MGGallery
    theme:                 mooDoo.2
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          mg_gallery
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title:                Galerías de fotos
        fields:
          count_photos:       {label: C.}
        display:              [title, description, count_photos]
        object_actions:
          _edit:              ~
          _delete:            ~
          show:
      filter:                 ~
      form:                   ~
      edit:                   ~
      new:                    ~