generator:
  class:                      sfDoctrineGenerator
  param:
    model_class:              Event
    theme:                    mooDoo.2
    non_verbose_templates:    true
    with_show:                false
    singular:                 ~
    plural:                   ~
    route_prefix:             event
    with_doctrine_route:      true
    actions_base_class:       sfActions

    config:
      actions: ~
      fields:  ~

      list:
        display:               [ _thumb, title, _cats, date, due_date ]
        fields:
          cats:
            label:              Categories
        actions:
          _new:                  { label: '&nbsp;', atts: {title: Add Event } }
      filter:  ~

      form:
        class:                EventAdminForm
        fields:
          Parent:             { name: Parent Event }
        display:              [ title, author_id, description, date, publication_date, due_date, sticky, mugshot, main_slideshow, event_cat ]

      edit:
        title:                  Edit Event
        actions:
          _list:                  { label: '&nbsp;', atts: {title: Back to list } }
          _delete:                { label: '&nbsp;', atts: {title: Delete } }
          _save:                  { label: '&nbsp;', atts: {title: Save } }
      new:
        title:                  New Event
        actions:
          _list:                  { label: '&nbsp;', atts: {title: Back to list } }
          _save:                  { label: '&nbsp;', atts: {title: Save } }
          _save_and_add:          { label: '&nbsp;', atts: {title: Save and add } }