generator:
  class: sfDoctrineGenerator
  param:
    model_class:                  sfGuardUser
    theme:                        mooDoo.2
    non_verbose_templates:        true
    with_show:                    false
    singular:                     ~
    plural:                       ~
    route_prefix:                 sf_guard_user
    with_doctrine_route:          true
    actions_base_class:           sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display:                  [ username, is_active, is_super_admin, last_login ]
        actions:
          _new:                  { label: '&nbsp;', atts: {title: Add user } }
      filter:  ~
      form:
        class:                    UserAdminForm

      edit:
        title:                  Edit User
        actions:
          _list:                  { label: '&nbsp;', atts: {title: Back to list } }
          _delete:                { label: '&nbsp;', atts: {title: Delete } }
          _save:                  { label: '&nbsp;', atts: {title: Save } }
      new:
        title:                  New User
        actions:
          _list:                  { label: '&nbsp;', atts: {title: Back to list } }
          _save:                  { label: '&nbsp;', atts: {title: Save } }
          _save_and_add:          { label: '&nbsp;', atts: {title: Save and add } }