generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Category
    theme:                 mooDoo.2
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          category
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display:          [ parent, title, created_at ]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
