generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Category
    theme:                 mooDoo.2
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          category
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display:          [ parent, title, created_at ]
      actions:
          _new:                  { label: '&nbsp;', atts: {title: Add category } }
      filter:  ~
      form:    ~
      edit:
        title:                  Edit Category
        actions:
          _list:                  { label: '&nbsp;', atts: {title: Back to list } }
          _delete:                { label: '&nbsp;', atts: {title: Delete } }
          _save:                  { label: '&nbsp;', atts: {title: Save } }
      new:
        title:                  New Category
        actions:
          _list:                  { label: '&nbsp;', atts: {title: Back to list } }
          _save:                  { label: '&nbsp;', atts: {title: Save } }
          _save_and_add:          { label: '&nbsp;', atts: {title: Save and add } }