generator:
  class:                        sfDoctrineGenerator
  param:
    model_class:                Page
    theme:                      mooDoo.2
    non_verbose_templates:      true
    with_show:                  false
    singular:                   ~
    plural:                     ~
    route_prefix:               page
    with_doctrine_route:        true
    actions_base_class:         sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display:                [ parent, author, title, created_at ]
        fields:
          parent:
            label:              Parent page
      filter:  ~
      form:    ~

      edit:
        title:                  Edit Page

      new:
        title:                  New Page
