# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

sf_guard_signin:
  url:   /login
  param: { module: users, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: users, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: users, action: password }

vip:
  url:   /vip
  param: { module: pages, action: permalink, id:21 }

photos:
  url:   /fotos
  param: { module: photos, action: index }
  
events:
  url:   /espectaculos
  param: { module: events, action: index }

page_slug:
  url:   /:slug
  param: {module: pages, action: permalink }

page_child_slug:
  url:   /:parentslug/:slug
  param: {module: pages, action: permalink, level:1 }
  
# generic rules
# please, remove them by adding more specific rules
#default_index:
#  url:   /:module
#  param: { action: index }

#default:
#  url:   /:module/:action/*
