<?php

/**
 * Category
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7380 2010-03-15 21:07:50Z jwage $
 */
class Category extends BaseCategory
{
  public function save(Doctrine_Connection $conn = null) {

   $slug=Magic::slugify($this->getTitle());
   if ($this->isNew()){
        $i=0;
        do{
        $i++;
        $q = Doctrine::getTable('Category')->findOneBySlug($slug);
        if(!$q) {
          break;
        }
        else{
          $slug=Magic::slugify($this->getTitle());
          $slug.=$i;
         }
        } while($i);
        $this->setSlug($slug);
      }
      elseif ($slug != $this->getSlug()) {
        $i=0;
        do{
          $i++;
          $q = Doctrine::getTable('Category')->findOneBySlug($slug);
          if(!$q ) {
            $this->setSlug($slug);
            break;
          }
          else if($slug == $this->getSlug()) break;
          else{
            $slug=Magic::slugify($this->getTitle());
            $slug.=$i;
          }
        } while($i);

      }

    parent::save($conn);

  }
}
