<?php

/**
 * EventGallery
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    magic
 * @subpackage model
 * @author     Damian Suarez
 * @version    SVN: $Id: Builder.php 7380 2010-03-15 21:07:50Z jwage $
 */
class EventGallery extends BaseEventGallery
{
}
